import type { ContentTypeInfo, ResolvedFieldInfo, ParagraphFieldConfig } from '../parsers/index.js';

interface ContentTypeGenData {
  type: string;
  hasParagraphs: boolean;
  hasMediaLibrary: boolean;
  hasCkeditor: boolean;
  requiredNodeFields: ResolvedFieldInfo[];
  paragraphFields: ParagraphFieldConfig[];
  /** Primary paragraph field (most allowed types). */
  primaryParagraphField?: ParagraphFieldConfig;
  /** Secondary paragraph fields. */
  secondaryParagraphFields: ParagraphFieldConfig[];
}

/**
 * Generate the content-types.ts file content.
 */
export function generateContentTypes(
  contentTypes: ContentTypeInfo[],
  dataByType: Map<string, ContentTypeGenData>,
): string {
  const lines: string[] = [];

  // Header.
  lines.push('/**');
  lines.push(' * Auto-generated by drupal-e2e generator.');
  lines.push(' * Source: config/sync/ YAML files.');
  lines.push(' */');
  lines.push('');

  // CONTENT_TYPES array.
  lines.push('export const CONTENT_TYPES = [');
  for (const ct of contentTypes) {
    lines.push(`  '${ct.type}',`);
  }
  lines.push('] as const;');
  lines.push('');
  lines.push('export type ContentType = (typeof CONTENT_TYPES)[number];');
  lines.push('');

  // PARAGRAPHS_TYPES.
  const paragraphTypes = contentTypes.filter((ct) => dataByType.get(ct.type)?.hasParagraphs);
  lines.push('/** Content types that use the Paragraphs widget. */');
  lines.push('export const PARAGRAPHS_TYPES: ContentType[] = [');
  for (const ct of paragraphTypes) {
    lines.push(`  '${ct.type}',`);
  }
  lines.push('];');
  lines.push('');

  // MEDIA_LIBRARY_TYPES.
  const mediaTypes = contentTypes.filter((ct) => dataByType.get(ct.type)?.hasMediaLibrary);
  lines.push('/** Content types that use the Media Library widget. */');
  lines.push('export const MEDIA_LIBRARY_TYPES: ContentType[] = [');
  for (const ct of mediaTypes) {
    lines.push(`  '${ct.type}',`);
  }
  lines.push('];');
  lines.push('');

  // CKEDITOR_TYPES.
  const ckeditorTypes = contentTypes.filter((ct) => dataByType.get(ct.type)?.hasCkeditor);
  lines.push('/** Content types that use CKEditor 5 (text_textarea or text_textarea_with_summary). */');
  lines.push('export const CKEDITOR_TYPES: ContentType[] = [');
  for (const ct of ckeditorTypes) {
    lines.push(`  '${ct.type}',`);
  }
  lines.push('];');
  lines.push('');

  // SIMPLE_TYPES.
  const simpleTypes = contentTypes.filter((ct) => !dataByType.get(ct.type)?.hasParagraphs);
  lines.push('/**');
  lines.push(' * Simple content types: fill title + CKEditor body only (no paragraphs).');
  lines.push(' */');
  lines.push('export const SIMPLE_TYPES: ContentType[] = [');
  for (const ct of simpleTypes) {
    lines.push(`  '${ct.type}',`);
  }
  lines.push('];');
  lines.push('');

  // ParagraphFieldConfig interface.
  lines.push('/**');
  lines.push(' * Paragraph field mapping per content type.');
  lines.push(' *');
  lines.push(' * - primary: The main paragraph field — all allowed types get added here.');
  lines.push(' * - secondary: Sidebar / ancillary fields — add one simple paragraph each.');
  lines.push(' */');
  lines.push('export interface ParagraphFieldConfig {');
  lines.push('  primary: {');
  lines.push('    field: string;');
  lines.push('    allowedTypes: string[];');
  lines.push('  };');
  lines.push('  secondary?: {');
  lines.push('    field: string;');
  lines.push('    addType: string;');
  lines.push('  }[];');
  lines.push('}');
  lines.push('');

  // NodeFieldStrategy type.
  lines.push('/**');
  lines.push(' * Required node-level fields (beyond title) that must be filled per content type.');
  lines.push(' * Each entry describes the field name, widget type, and how to fill it.');
  lines.push(' */');
  lines.push('export type NodeFieldStrategy =');
  lines.push("  | { widget: 'ckeditor'; fieldName: string }");
  lines.push("  | { widget: 'textarea'; fieldName: string }");
  lines.push("  | { widget: 'text'; fieldName: string }");
  lines.push("  | { widget: 'select'; fieldName: string }");
  lines.push("  | { widget: 'radios'; fieldName: string }");
  lines.push("  | { widget: 'checkboxes'; fieldName: string }");
  lines.push("  | { widget: 'media'; fieldName: string }");
  lines.push("  | { widget: 'smartdate'; fieldName: string }");
  lines.push("  | { widget: 'cshs'; fieldName: string };");
  lines.push('');

  // REQUIRED_NODE_FIELDS.
  lines.push('export const REQUIRED_NODE_FIELDS: Partial<Record<ContentType, NodeFieldStrategy[]>> = {');
  for (const ct of contentTypes) {
    const data = dataByType.get(ct.type);
    if (!data || data.requiredNodeFields.length === 0) continue;

    lines.push(`  ${ct.type}: [`);
    for (const field of data.requiredNodeFields) {
      lines.push(`    { widget: '${field.strategy}', fieldName: '${field.fieldName}' },`);
    }
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');

  // PARAGRAPH_FIELDS.
  lines.push('export const PARAGRAPH_FIELDS: Partial<Record<ContentType, ParagraphFieldConfig>> = {');
  for (const ct of contentTypes) {
    const data = dataByType.get(ct.type);
    if (!data || !data.primaryParagraphField) continue;

    const primary = data.primaryParagraphField;
    const secondary = data.secondaryParagraphFields;

    lines.push(`  ${ct.type}: {`);
    lines.push('    primary: {');
    lines.push(`      field: '${primary.fieldName}',`);
    lines.push('      allowedTypes: [');

    // Format allowed types, wrapping lines at reasonable length.
    const typeStrings = primary.allowedTypes.map((t) => `'${t}'`);
    let currentLine = '        ';
    for (let i = 0; i < typeStrings.length; i++) {
      const sep = i < typeStrings.length - 1 ? ', ' : ',';
      if (currentLine.length + typeStrings[i].length + sep.length > 95) {
        lines.push(currentLine);
        currentLine = '        ' + typeStrings[i] + sep;
      } else {
        currentLine += typeStrings[i] + sep;
      }
    }
    if (currentLine.trim()) lines.push(currentLine);

    lines.push('      ],');
    lines.push('    },');

    if (secondary.length > 0) {
      lines.push('    secondary: [');
      for (const sec of secondary) {
        // Default addType: 'text' if available, otherwise first allowed type.
        const addType = sec.allowedTypes.includes('text')
          ? 'text'
          : sec.allowedTypes[0] ?? 'text';
        lines.push(`      { field: '${sec.fieldName}', addType: '${addType}' },`);
      }
      lines.push('    ],');
    }

    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

export type { ContentTypeGenData };
