import type { ParagraphTypeInfo, ResolvedFieldInfo, NestingInfo } from '../parsers/index.js';

interface ParagraphGenData {
  id: string;
  label: string;
  fields: ResolvedFieldInfo[];
  nested?: NestingInfo;
}

/**
 * Map from FieldStrategyType (parser) to the paragraph-map FieldStrategy type string.
 * These must match the FieldStrategy type union in the generated file.
 */
function strategyToType(strategy: string): string {
  switch (strategy) {
    case 'ckeditor': return 'ckeditor';
    case 'text': return 'text';
    case 'textarea': return 'textarea';
    case 'select': return 'select';
    case 'boolean':
    case 'checkboxes':
    case 'radios':
      return 'boolean';
    case 'media': return 'media';
    case 'link': return 'link';
    default: return 'text';
  }
}

/**
 * Generate the paragraph-map.ts file content.
 */
export function generateParagraphMap(
  paragraphData: Map<string, ParagraphGenData>,
): string {
  const lines: string[] = [];

  // Header.
  lines.push('/**');
  lines.push(' * Paragraph type registry.');
  lines.push(' *');
  lines.push(' * Auto-generated by drupal-e2e generator.');
  lines.push(' * Source: config/sync/ YAML files.');
  lines.push(' *');
  lines.push(' * Maps every paragraph bundle to its human-readable label, required fields,');
  lines.push(' * and nesting configuration.');
  lines.push(' */');
  lines.push('');
  lines.push("import { SITE_CONFIG } from '../site-config';");
  lines.push('');

  // FieldStrategy type.
  lines.push('// ── Field fill strategies ───────────────────────────────────────────────');
  lines.push('');
  lines.push('export type FieldStrategy =');
  lines.push("  | { type: 'text'; selector?: string }");
  lines.push("  | { type: 'ckeditor' }");
  lines.push("  | { type: 'textarea' }");
  lines.push("  | { type: 'select' }");
  lines.push("  | { type: 'boolean' }");
  lines.push("  | { type: 'media' }");
  lines.push("  | { type: 'link' };");
  lines.push('');

  // FieldDef interface.
  lines.push('export interface FieldDef {');
  lines.push('  name: string;');
  lines.push('  strategy: FieldStrategy;');
  lines.push('}');
  lines.push('');

  // NestedDef interface.
  lines.push('export interface NestedDef {');
  lines.push('  /** The paragraph reference field that holds children. */');
  lines.push('  field: string;');
  lines.push('  /** The child paragraph bundle to add. */');
  lines.push('  childType: string;');
  lines.push('}');
  lines.push('');

  // ParagraphDef interface.
  lines.push('export interface ParagraphDef {');
  lines.push('  /** Human-readable label (must match the "Add {label}" button text). */');
  lines.push('  label: string;');
  lines.push('  /** Required fields to fill. Empty array = no required fields. */');
  lines.push('  fields: FieldDef[];');
  lines.push('  /** If this is a container type, describes the nested child. */');
  lines.push('  nested?: NestedDef;');
  lines.push('}');
  lines.push('');

  // Registry.
  lines.push('// ── Registry ────────────────────────────────────────────────────────────');
  lines.push('');
  lines.push('export const PARAGRAPH_MAP: Record<string, ParagraphDef> = {');

  // Track written entries to avoid duplicates.
  const written = new Set<string>();

  const entries = Array.from(paragraphData.values());
  const containers = entries.filter((e) => e.nested);
  const simple = entries.filter((e) => !e.nested);

  // Child types used in nesting.
  const childTypes = new Set(containers.flatMap((c) => c.nested!.childTypes));

  // Top-level simple types (not children of containers and not containers).
  const topLevelSimple = simple.filter((e) => !childTypes.has(e.id));

  // Write simple content paragraphs.
  if (topLevelSimple.length > 0) {
    lines.push('  // Simple content paragraphs');
    for (const entry of topLevelSimple) {
      if (written.has(entry.id)) continue;
      written.add(entry.id);
      writeParagraphEntry(lines, entry);
    }
    lines.push('');
  }

  // Write container paragraphs and their children.
  if (containers.length > 0) {
    lines.push('  // Container paragraphs (with nested children)');
    for (const entry of containers) {
      if (written.has(entry.id)) continue;
      written.add(entry.id);
      writeParagraphEntry(lines, entry);

      // Write child types immediately after parent.
      for (const childId of entry.nested!.childTypes) {
        if (written.has(childId)) continue;
        const child = paragraphData.get(childId);
        if (child) {
          written.add(childId);
          writeParagraphEntry(lines, child);
        }
      }
    }
    lines.push('');
  }

  // Write any remaining entries not yet written.
  for (const entry of entries) {
    if (written.has(entry.id)) continue;
    written.add(entry.id);
    writeParagraphEntry(lines, entry);
  }

  lines.push('};');
  lines.push('');

  // SKIPPED_PARAGRAPH_TYPES.
  lines.push('/**');
  lines.push(' * Paragraph types that are skipped in UI tests because they require');
  lines.push(" * entity reference autocomplete fields that can't be reliably filled.");
  lines.push(' */');
  lines.push('export const SKIPPED_PARAGRAPH_TYPES = new Set(SITE_CONFIG.skippedParagraphTypes);');
  lines.push('');

  return lines.join('\n');
}

function writeParagraphEntry(lines: string[], entry: ParagraphGenData): void {
  lines.push(`  ${entry.id}: {`);
  lines.push(`    label: '${escapeSingleQuote(entry.label)}',`);

  if (entry.fields.length === 0) {
    lines.push('    fields: [],');
  } else {
    lines.push('    fields: [');
    for (const field of entry.fields) {
      const stratType = strategyToType(field.strategy);
      lines.push(`      { name: '${field.fieldName}', strategy: { type: '${stratType}' } },`);
    }
    lines.push('    ],');
  }

  if (entry.nested) {
    // Prefer 'text' as child type when available (simplest to fill in tests).
    const childTypes = entry.nested.childTypes;
    const primaryChild = childTypes.includes('text') ? 'text' :
      childTypes.find((t) => !['block_placer', 'view_placer'].includes(t)) ?? childTypes[0];
    lines.push(`    nested: { field: '${entry.nested.field}', childType: '${primaryChild}' },`);
  }

  lines.push('  },');
}

function escapeSingleQuote(s: string): string {
  return s.replace(/'/g, "\\'");
}

export type { ParagraphGenData };
