import type { ResolvedFieldInfo } from '../parsers/index.js';

interface SiteConfigData {
  baseUrl: string;
  skippedParagraphTypes: string[];
  consoleErrorIgnores: string[];
  globalRequiredFields: ResolvedFieldInfo[];
}

/**
 * Generate the site-config.ts file content.
 */
export function generateSiteConfig(data: SiteConfigData): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * Site-specific configuration for Drupal E2E tests.');
  lines.push(' *');
  lines.push(' * Auto-generated by drupal-e2e generator.');
  lines.push(' * Review and adjust values marked with TODO after generation.');
  lines.push(' */');
  lines.push('');
  lines.push('export const SITE_CONFIG = {');

  // Base URL.
  lines.push('  /** Auto-detected from .ddev/config.yaml. */');
  lines.push(`  baseUrl: '${data.baseUrl}',`);
  lines.push('');

  // Skipped paragraph types.
  lines.push('  /**');
  lines.push('   * Paragraph types to skip in tests.');
  lines.push('   * TODO: Review — types with entity_reference_autocomplete or external API dependencies');
  lines.push('   * should be listed here.');
  lines.push('   */');
  if (data.skippedParagraphTypes.length === 0) {
    lines.push('  skippedParagraphTypes: [] as string[],');
  } else {
    lines.push('  skippedParagraphTypes: [');
    for (const t of data.skippedParagraphTypes) {
      lines.push(`    '${t}',`);
    }
    lines.push('  ],');
  }
  lines.push('');

  // Console error ignores.
  lines.push('  /**');
  lines.push('   * Extra console error patterns to ignore (theme-specific, contrib modules).');
  lines.push('   * TODO: Review — add patterns for known benign console errors from your theme.');
  lines.push('   */');
  if (data.consoleErrorIgnores.length === 0) {
    lines.push('  consoleErrorIgnores: [] as RegExp[],');
  } else {
    lines.push('  consoleErrorIgnores: [');
    for (const pattern of data.consoleErrorIgnores) {
      lines.push(`    ${pattern},`);
    }
    lines.push('  ],');
  }
  lines.push('');

  // Global required fields.
  lines.push('  /**');
  lines.push('   * Fields that are required on ALL content types (e.g. editorial sections, domain access).');
  lines.push('   * These get filled before per-type required fields.');
  lines.push('   * TODO: Review — verify these fields exist and are required on every content type.');
  lines.push('   */');
  if (data.globalRequiredFields.length === 0) {
    lines.push("  globalRequiredFields: [] as { fieldName: string; widget: string }[],");
  } else {
    lines.push('  globalRequiredFields: [');
    for (const field of data.globalRequiredFields) {
      lines.push(`    { fieldName: '${field.fieldName}', widget: '${field.strategy}' },`);
    }
    lines.push('  ],');
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

export type { SiteConfigData };
